version: '3'


services:
 jenkins-docker:
   container_name: jenkins-docker
   image: docker:dind
   restart: "no"
   privileged: true
   networks:
     - jenkins
   environment:
     DOCKER_TLS_CERTDIR: /certs
   volumes:
     - jenkins-docker-certs:/certs/client
     - jenkins-data:/var/jenkins_home
   ports:
     - "2376:2376"
   command: ["--storage-driver", "overlay2"]
  jenkins-blueocean:
   build:
     context: .
     dockerfile: Dockerfile
   image: myjenkins-blueocean:2.387.1-1
   container_name: jenkins-blueocean
   restart: on-failure
   networks:
     - jenkins
   environment:
     DOCKER_HOST: tcp://jenkins-docker:2376
     DOCKER_CERT_PATH: /certs/client
     DOCKER_TLS_VERIFY: "1"
   volumes:
     - jenkins-data:/var/jenkins_home
     - jenkins-docker-certs:/certs/client:ro
   ports:
     - "8080:8080"
     - "50000:50000"


networks:
 jenkins:
   driver: bridge


volumes:
 jenkins-data:
 jenkins-docker-certs:
